"""
Enhanced Execution Agent v3

Improvements:
1. Element finding wrapper with fallback strategies
2. Better error categorization (not found vs timeout vs wrong element)
3. Detailed error context for debugging
4. Screenshot + DOM capture with error markers
5. Console error tracking with context
"""

import uuid
import traceback
from datetime import datetime
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError
from clients import s3, ARTIFACTS_BUCKET

EXECUTION_TIMEOUT = 30000  # 30 seconds


class ElementFinder:
    """
    Wrapper that provides multi-strategy element finding.
    Useful for execution environments that need to try multiple locator strategies.
    """
    def __init__(self, page):
        self.page = page
        self.failed_selectors = []
    
    def find_element(self, strategies: list, timeout: int = 5000) -> object:
        """
        Try multiple selector strategies in order until one succeeds.
        
        Args:
            strategies: List of tuples (name, selector_callable)
            timeout: Wait timeout per strategy
        
        Returns:
            Located element or raises Exception with all attempts
        """
        for strategy_name, selector_fn in strategies:
            try:
                element = selector_fn()
                element.wait_for(timeout=timeout)
                if element.is_visible():
                    return element
            except Exception as e:
                self.failed_selectors.append({
                    'strategy': strategy_name,
                    'error': str(e)[:200]
                })
                continue
        
        # All strategies failed
        attempts = "\n".join([
            f"  - {s['strategy']}: {s['error']}"
            for s in self.failed_selectors
        ])
        raise Exception(
            f"Element not found with any strategy:\n{attempts}"
        )


def execution_agent_node(state: dict) -> dict:
    """
    Execute the Playwright script generated by the scenario agent.
    
    Enhanced to capture:
    - Detailed error context (which selector, which element, why)
    - Console errors and warnings  
    - Network failures
    - Screenshots and DOM snapshots with error context
    """
    run_id = state["run_id"]
    attempt = state.get("attempt", 1)
    print(f"\n[execution-agent] running script for run {run_id} (attempt {attempt})")
    
    console_messages = {
        "errors": [],
        "warnings": [],
        "logs": [],
    }
    
    passed = True
    error_message = None
    error_context = None
    execution_exception = None
    
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            
            context = browser.new_context(
                viewport={"width": 1920, "height": 1080},
                ignore_https_errors=True,
            )
            page = context.new_page()
            
            # Set default timeout
            page.set_default_timeout(EXECUTION_TIMEOUT)
            page.set_default_navigation_timeout(EXECUTION_TIMEOUT)
            
            # Monitor console
            def handle_console_msg(msg):
                if msg.type == "error":
                    console_messages["errors"].append(msg.text)
                elif msg.type == "warning":
                    console_messages["warnings"].append(msg.text)
                else:
                    console_messages["logs"].append(msg.text)
                print(f"  [console-{msg.type}] {msg.text}")
            
            # Monitor network
            failed_requests = []
            def handle_request_failed(request):
                failed_requests.append({
                    "url": request.url,
                    "failure": str(request.failure or "Unknown")[:200]
                })
            
            page.on("console", handle_console_msg)
            page.on("requestfailed", handle_request_failed)
            
            # Navigate
            print(f"[execution-agent] navigating to {state['url']}...")
            try:
                page.goto(state["url"], wait_until="load")
            except PlaywrightTimeoutError:
                error_message = f"Navigation timeout: page did not load within {EXECUTION_TIMEOUT}ms"
                error_context = f"""Navigation failed. Possible causes:
- Server not responding
- Network issues
- Page stuck loading resources
- Invalid URL: {state['url']}"""
                passed = False
            
            # Execute script
            if passed:
                print(f"[execution-agent] executing test script...")
                try:
                    # Provide helper class to execution context
                    exec(state["playwright_script"], {
                        "page": page,
                        "console_errors": console_messages["errors"],
                        "print": print,
                        "ElementFinder": ElementFinder,
                    })
                    print(f"[execution-agent] script executed successfully")
                
                except PlaywrightTimeoutError as e:
                    error_str = str(e)
                    
                    # Try to extract which locator timed out
                    if "waiting for" in error_str.lower():
                        # Example: "Error: Timeout 30000ms exceeded. waiting for get_by_text(\"Log in\") to be visible"
                        locator_part = error_str.split("waiting for")[-1].split("to")[0].strip()
                        error_message = f"Timeout: element not found or not visible: {locator_part}"
                    else:
                        error_message = f"Timeout: {error_str[:150]}"
                    
                    # Provide helpful context
                    page_source = page.content()
                    error_context = f"""Element interaction timed out.

Likely causes:
1. Element doesn't exist on page (selector mismatch)
2. Element exists but is hidden/covered by another element
3. Page structure changed since test was generated
4. JavaScript is still running and element not yet attached

Debug info:
- Page URL: {page.url}
- Page size: {page.evaluate("() => document.body.outerHTML.length")} bytes
- Errors on page: {len(console_messages['errors'])}
- Failed requests: {len(failed_requests)}

{f'First error: {console_messages["errors"][0]}' if console_messages['errors'] else ''}
"""
                    passed = False
                
                except AssertionError as e:
                    error_message = f"Assertion failed: {str(e)[:100]}"
                    error_context = f"""A test assertion did not pass.

Assertion: {str(e)}

This means the actual result did not match what the test expected.
Check if:
- Application behavior changed
- Page redirected to unexpected location
- Expected text/element not present
"""
                    passed = False
                
                except Exception as e:
                    error_type = type(e).__name__
                    error_str = str(e)
                    
                    # Try to extract useful info from error
                    if "strict mode" in error_str.lower():
                        error_message = f"Strict mode violation: selector matched multiple elements"
                        error_context = f"""The selector is ambiguous and matches 2+ elements.

Error: {error_str[:300]}

Solution: Use more specific selector (prefer ID over text, prefer data-testid over class)
"""
                    else:
                        error_message = f"{error_type}: {error_str[:100]}"
                        error_context = f"""{error_type}: {error_str}

Traceback (last 500 chars):
{traceback.format_exc()[-500:]}
"""
                    passed = False
                    execution_exception = e
            
            # Capture diagnostics
            print(f"[execution-agent] capturing diagnostics...")
            
            try:
                screenshot_bytes = page.screenshot(full_page=True)
                dom_html = page.content()
                
                # Store artifacts
                tenant_id = state["tenant_id"]
                project_id = state["project_id"]
                screenshot_key = f"{tenant_id}/{project_id}/{run_id}/screenshot_attempt_{attempt}.png"
                dom_key = f"{tenant_id}/{project_id}/{run_id}/dom_attempt_{attempt}.html"
                
                s3.put_object(
                    Bucket=ARTIFACTS_BUCKET,
                    Key=screenshot_key,
                    Body=screenshot_bytes,
                    ContentType="image/png"
                )
                s3.put_object(
                    Bucket=ARTIFACTS_BUCKET,
                    Key=dom_key,
                    Body=dom_html.encode("utf-8"),
                    ContentType="text/html"
                )
                print(f"[execution-agent] stored screenshot and DOM in S3")
            
            except Exception as e:
                print(f"[execution-agent] warning: could not store artifacts: {e}")
                screenshot_key = None
                dom_key = None
            
            browser.close()
    
    except Exception as e:
        print(f"[execution-agent] fatal error: {e}")
        error_message = f"Execution crashed: {str(e)[:100]}"
        error_context = f"""Test execution crashed before completion.

Error: {str(e)}

Traceback:
{traceback.format_exc()[-800:]}

This could indicate:
- Browser launch failure
- Invalid test script syntax
- Missing dependencies
- System resource issues
"""
        passed = False
        screenshot_key = None
        dom_key = None
    
    # Build execution result
    execution_result = {
        "pageUrl": state["url"],
        "passed": passed,
        "error": error_message,
        "error_context": error_context,
        "error_type": type(execution_exception).__name__ if execution_exception else None,
        "console_errors": console_messages["errors"],
        "console_warnings": console_messages["warnings"],
        "console_logs": console_messages["logs"],
        "screenshot_s3_path": screenshot_key,
        "dom_s3_path": dom_key,
        "attempt": attempt,
    }
    
    print(f"\n[execution-agent] result summary:")
    print(f"  Passed: {passed}")
    print(f"  Console errors: {len(console_messages['errors'])}")
    print(f"  Console warnings: {len(console_messages['warnings'])}")
    if error_message:
        print(f"  Error: {error_message}")
    
    return {
        **state,
        "execution_results": [execution_result],
        "status": "passed" if passed else "failed",
    }