"""
Enhanced Execution Agent

Improvements:
1. Better error context capture (which element failed, why)
2. Console error tracking
3. Network error detection
4. Screenshot AND DOM capture on failure
5. Clear error messages for self-healing
"""

import uuid
import traceback
from datetime import datetime
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError
from clients import s3, ARTIFACTS_BUCKET

# Maximum retries for individual timeouts
EXECUTION_TIMEOUT = 30000  # 30 seconds


def execution_agent_node(state: dict) -> dict:
    """
    Execute the Playwright script generated by the scenario agent.
    
    Captures:
    - Pass/fail status
    - Error messages with context
    - Console errors and warnings
    - Screenshots on failure
    - DOM snapshots for debugging
    """
    run_id = state["run_id"]
    print(f"\n[execution-agent] running generated script for run {run_id}")
    
    console_messages = {
        "errors": [],
        "warnings": [],
        "logs": [],
    }
    
    passed = True
    error_message = None
    error_context = None  # More detailed context about what failed
    
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            
            # Create a context with better defaults
            context = browser.new_context(
                viewport={"width": 1920, "height": 1080},
                ignore_https_errors=True,
            )
            page = context.new_page()
            
            # Set default timeout
            page.set_default_timeout(EXECUTION_TIMEOUT)
            page.set_default_navigation_timeout(EXECUTION_TIMEOUT)
            
            # Monitor console
            def handle_console_msg(msg):
                if msg.type == "error":
                    console_messages["errors"].append(msg.text)
                elif msg.type == "warning":
                    console_messages["warnings"].append(msg.text)
                else:
                    console_messages["logs"].append(msg.text)
                print(f"  [console-{msg.type}] {msg.text}")
            
            # Monitor network errors
            failed_requests = []
            def handle_request_failed(request):
                failed_requests.append({
                    "url": request.url,
                    "failure": request.failure or "Unknown"
                })
            
            page.on("console", handle_console_msg)
            page.on("requestfailed", handle_request_failed)
            
            print(f"[execution-agent] navigating to {state['url']}...")
            try:
                page.goto(state["url"], wait_until="load")
            except PlaywrightTimeoutError:
                error_message = f"Navigation timeout: page did not load within {EXECUTION_TIMEOUT}ms"
                error_context = "The page took too long to load. Check network or server."
                passed = False
            
            if passed:
                print(f"[execution-agent] executing test script...")
                try:
                    # Execute the script body
                    # The script has access to `page` and `console_errors` dict
                    exec(state["playwright_script"], {
                        "page": page,
                        "console_errors": console_messages["errors"],
                        "print": print,  # Allow print statements for debugging
                    })
                    print(f"[execution-agent] script executed successfully")
                
                except PlaywrightTimeoutError as e:
                    # Extract which locator timed out
                    error_str = str(e)
                    if "waiting for" in error_str:
                        locator = error_str.split("waiting for")[-1].split("to")[0].strip()
                        error_message = f"Timeout waiting for element: {locator}"
                        error_context = f"Could not find or interact with: {locator}. The element may not exist on the page, may be hidden, or the page structure may have changed."
                    else:
                        error_message = f"Timeout: {error_str[:200]}"
                        error_context = "An interaction timed out. Check selectors and page structure."
                    passed = False
                
                except AssertionError as e:
                    error_message = f"Assertion failed: {str(e)}"
                    error_context = "A test assertion did not pass. The application behavior may not match expectations."
                    passed = False
                
                except Exception as e:
                    error_message = f"{type(e).__name__}: {str(e)}"
                    error_context = traceback.format_exc()[-500:]  # Last 500 chars of traceback
                    passed = False
            
            # Always capture screenshots and DOM
            print(f"[execution-agent] capturing diagnostics...")
            screenshot_bytes = page.screenshot(full_page=True)
            dom_html = page.content()
            
            # Store in S3
            tenant_id = state["tenant_id"]
            project_id = state["project_id"]
            screenshot_key = f"{tenant_id}/{project_id}/{run_id}/screenshot.png"
            dom_key = f"{tenant_id}/{project_id}/{run_id}/dom.html"
            
            try:
                s3.put_object(
                    Bucket=ARTIFACTS_BUCKET,
                    Key=screenshot_key,
                    Body=screenshot_bytes,
                    ContentType="image/png"
                )
                s3.put_object(
                    Bucket=ARTIFACTS_BUCKET,
                    Key=dom_key,
                    Body=dom_html.encode("utf-8"),
                    ContentType="text/html"
                )
                print(f"[execution-agent] stored screenshot and DOM in S3")
            except Exception as e:
                print(f"[execution-agent] warning: could not store artifacts: {e}")
            
            browser.close()
    
    except Exception as e:
        print(f"[execution-agent] fatal error: {e}")
        error_message = f"Execution error: {str(e)}"
        error_context = traceback.format_exc()
        passed = False
        screenshot_key = None
        dom_key = None
    
    # Build execution result
    execution_result = {
        "pageUrl": state["url"],
        "passed": passed,
        "error": error_message,
        "error_context": error_context,  # <-- Better error detail
        "console_errors": console_messages["errors"],
        "console_warnings": console_messages["warnings"],
        "console_logs": console_messages["logs"],
        "screenshot_s3_path": screenshot_key,
        "dom_s3_path": dom_key,
    }
    
    print(f"\n[execution-agent] result summary:")
    print(f"  Passed: {passed}")
    print(f"  Console errors: {len(console_messages['errors'])}")
    print(f"  Console warnings: {len(console_messages['warnings'])}")
    if error_message:
        print(f"  Error: {error_message}")
    
    return {
        **state,
        "execution_results": [execution_result],
        "status": "executing" if passed else "failed",
    }